---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: ingress-admin-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ingress-cluster-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingress"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: ingress-admin-ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-cluster-role
subjects:
- kind: ServiceAccount
  name: ingress-admin-sa
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ingress-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-manager 
  template:
    metadata:
      labels:
        app: ingress-manager
    spec:
      serviceAccountName: ingress-admin-sa
      containers:
      - name: ingress-manager
        image: 

